CREATE TABLE IF NOT EXISTS patients (
 patient_id VARCHAR(64) PRIMARY KEY,
 display_name VARCHAR(128) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS vitals (
 id BIGSERIAL PRIMARY KEY,
 patient_id VARCHAR(64) NOT NULL,
 ts TIMESTAMPTZ NOT NULL,
 heart_rate DOUBLE PRECISION NOT NULL,
 spo2 DOUBLE PRECISION NOT NULL,
 systolic_bp DOUBLE PRECISION NOT NULL,
 diastolic_bp DOUBLE PRECISION NOT NULL,
 temperature DOUBLE PRECISION NOT NULL,
 respiratory_rate DOUBLE PRECISION NOT NULL,
 accepted BOOLEAN NOT NULL DEFAULT TRUE,
 anomaly_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
 UNIQUE(patient_id, ts)
);
CREATE INDEX IF NOT EXISTS idx_vitals_patient_ts ON vitals(patient_id, ts DESC);
CREATE TABLE IF NOT EXISTS alerts (
 id BIGSERIAL PRIMARY KEY,
 patient_id VARCHAR(64) NOT NULL,
 ts TIMESTAMPTZ NOT NULL,
 severity VARCHAR(16) NOT NULL,
 risk DOUBLE PRECISION NOT NULL,
 factors JSONB NOT NULL,
 message TEXT NOT NULL,
 acknowledged BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_alerts_patient_ts ON alerts(patient_id, ts DESC);
CREATE TABLE IF NOT EXISTS audit_log (
 id BIGSERIAL PRIMARY KEY,
 actor VARCHAR(128), action VARCHAR(128) NOT NULL,
 patient_id VARCHAR(64), ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);
INSERT INTO patients(patient_id, display_name) VALUES ('P001','Demo Patient') ON CONFLICT DO NOTHING;
